# Generated by Django 4.2.7 on 2023-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=8)),
                ('unit_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
