# Generated by Django 5.0 on 2024-04-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degrees', models.CharField(choices=[('1', 'Bachelor of Advanced Computing'), ('2', 'Bachelor of Science'), ('3', 'Bachelor of Interaction Design')], max_length=256)),
                ('majors', models.CharField(choices=[('1', 'Computer Science'), ('2', 'Data Science'), ('3', 'Software Development')], max_length=256)),
                ('second_majors', models.CharField(choices=[('1', 'Computer Science'), ('2', 'Data Science'), ('3', 'Software Development'), ('4', 'Minors')], max_length=256)),
                ('minors', models.CharField(choices=[('1', 'Computer Science'), ('2', 'Data Science'), ('3', 'Software Development'), ('4', 'Minors')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=8)),
                ('unit_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
